apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocess-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocess
  template:
    metadata:
      labels:
        app: preprocess
    spec:
      containers:
      - name: preprocess
        image: preprocess:1.0.0         
        imagePullPolicy: IfNotPresent    
        env:
        - name: DATA_ROOT
          value: /data
        ports:
        - containerPort: 8000            
        volumeMounts:
        - name: data-vol
          mountPath: /data
        readinessProbe:
          httpGet: { path: /healthz, port: 8000 }
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /healthz, port: 8000 }
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: preprocess-svc
spec:
  selector:
    app: preprocess
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30080          

