apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: yfyyg2005/ui-api:v52
        imagePullPolicy: IfNotPresent
        env:
        - name: INFERENCE_URL
          value: http://inference-svc/predict   
        - name: TRAIN_URL
          value: http://training-svc/train     
        ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: ui-svc
spec:
  selector:
    app: ui
  type: NodePort
  ports:
  - port: 80
    targetPort: 8001
    nodePort: 30082
    protocol: TCP
