apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: yfyyg2005/ui-api:v2   # Docker Hub image you pushed
        imagePullPolicy: IfNotPresent
        env:
        - name: INFERENCE_URL
          value: http://inference-svc:5000/predict   # Service name + port inside cluster
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ui-svc
spec:
  selector:
    app: ui
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30082  # Pick an unused port to expose
    protocol: TCP


